### ISSUE TITLE
[ngtsc] use angular.json

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ng-ast/ngast#29]
Currently ngast uses the root typescript configuration to scan the project.
By using the angular.json file as a reference instead we could : 
- Provide more information concerning the workspace structure.
- Lazily analyze each project instead of analyzing the whole workspace.
- Being able to provide different APIs depending on the `projectType`.
- Support `stylePreprocessorOptions` for the css parser.

How to do that : 
1. Parse angular.json file
- Either use a simple `JSON.parse(fs.readFileSync('angular.json'))` (no more dependency but no typing).
- Or use the method `readWorkspace` of `@angular-devkit/core` (strongly typed but another dependency).
2. Per project look for the `tsConfig` field name under 'projects/:projectName/architect/build/options/tsconfig'.
3. Only instantiate the compiler once for all project.

**Comment by mgechev** [comment]
I'd suggest to ask developers to provide a specific `tsconfig.json` manually.

**Comment by GrandSchtroumpf** [comment]
Ok. so for you this should be done in another library if we want to take advantage of the angular.json information as describe above ?

**Comment by mgechev** [comment]
Yes, either this or let the consumer of `ngast` implement this functionaity.

**Comment by GrandSchtroumpf** [comment]
Ok, thx I'll try that.
