### ISSUE TITLE
[ngtsc] publish with next or canary tag

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ng-ast/ngast#31]
I'm building a vscode extension, and I would like to take advantage of the new version of ngast with the ngtsc compiler support.
Would it be possible to publish it with the tag `next` or `canary` depending how mature you consider the current state of the library.
Thanks.

**Comment by mgechev** [comment]
@GrandSchtroumpf I'd give you permissions to publish new releases.

**Comment by GrandSchtroumpf** [comment]
Thanks, it's "grandschtroumpf" too.
Do you have any recommendations or guideline to follow concerning the versions & tags ?
Should I wait to fix the @Inject issue before moving to latest ?

**Comment by mgechev** [comment]
I've been keeping ngast as an experimental (0 as major) because it steps on non-public APIs and its hard to guarantee compatibility with patch releases.

To indicate we're publishing a brand new API, I think we should use 0.5.0.

I think it's okay to move to latest.

**Comment by GrandSchtroumpf** [comment]
ngast@0.5.0 is out on npm now !
I'll write a medium article soon to describe the changes & publish a small vscode extension to play with it in a angular project.
