### ISSUE TITLE
Question: is there a way to speed up the initial analysis?

### ISSUE THREAD

**Issue by JPGygax68** [ng-ast/ngast#33]
Is there a way to save and reload the internal state of ngast ?

**Comment by JPGygax68** [comment]
Thank you for the explanation. There may be another approach actually: since, in 99% of the cases, the Angular compiler will be running in the background anyway, there might be a way to have it output the AST at the same time?

**Comment by mgechev** [comment]
I'd say that this would be nearly impossible to prioritize currently. I'd suggest to close the issue for now and revisit in a year or so. Then we can directly discuss in [angular/angular](https://github.com/angular/angular).

**Comment by mgechev** [comment]
Closing for now.
