### ISSUE TITLE
Question- Is there a way to not follow aot in ngast(v0.4.0)?

### ISSUE THREAD

**Issue by shikharka-magic** [ng-ast/ngast#34]
Lazy loaded modules gives error (The AOT collector does not support the arrow function)
```
@Component({
  ...
  providers: [{provide: server, useFactory: () => new Server()}]
})
```
**ERROR** - Function expressions are not supported in decorators

Is there a way to not follow aot in ngast(v0.4.0)?

**Comment by mgechev** [comment]
There's no way. We use the Angular compiler and if its unable to parse a file `ngast` fill fail as well.
