### ISSUE TITLE
Question - Could not resolve dependency with @angular/compiler@11.0.2

### ISSUE THREAD

**Issue by svoboda-rabstvo** [ng-ast/ngast#35]
I tried install latest version, but I have current error:

```bash
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"^10.0.0" from ngast@0.5.0
npm ERR! node_modules/ngast
npm ERR!   ngast@"*" from the root project
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
```

Maybe do you have any ideas? Without `force` installing, offcourse

My current version of `@angular/compiler` is `11`

**Comment by mgechev** [comment]
You should get support for v11 after [this PR](https://github.com/ng-ast/ngast/pull/36) goes in.

What are you using ngast for?

**Comment by svoboda-rabstvo** [comment]
For static analysis tools. For example: `ngx-translate-lint`

**Comment by mgechev** [comment]
It's out in 0.6.0.
