### ISSUE TITLE
No exported member 'ErroredTrait'.

### ISSUE THREAD

**Issue by georgebatalinski** [ng-ast/ngast#43]
```
node_modules/ngast/lib/ngtsc/symbol.d.ts:26:306 - error TS2694: Namespace '"@angular/compiler-cli/src/ngtsc/transform"' has no exported member 'ErroredTrait'.

26 export declare const isAnalysed: <A, B, C>(trait?: import("@angular/compiler-cli/src/ngtsc/transform").PendingTrait<A, B, C> | import("@angular/compiler-cli/src/ngtsc/transform").SkippedTrait<A, B, C> | AnalyzedTrait<A, B, C> | ResolvedTrait<A, B, C> | import("@angular/compiler-cli/src/ngtsc/transform").ErroredTrait<A, B, C> | undefined) => trait is AnalyzedTrait<A, B, C> | ResolvedTrait<A, B, C>;
```

**I noticed that remove the concept of an errored trait was undertaken here**
https://github.com/angular/angular/pull/39923

**ErroredTrait is no longer in the code** 
https://github.com/ng-ast/ngast/blob/master/lib/ngtsc/symbol.ts

**but it seems that the npm package still has the outdated code** 
"ngast@0.6.1"

Would this be the case?

**Comment by mgechev** [comment]
Yes, just fixed this yesterday. Feel free to update to 0.6.2.
